### ISSUE TITLE
Command-line usage

### ISSUE THREAD

**Issue by blokhin** [Exabyte-io/made.js#26]
Please, if possible, provide some examples of utility command-line usage.

**Comment by timurbazhirov** [comment]
Thanks for asking. I'm not exactly sure what you mean by command-line usage since this repository is a JavaScript library. There are certain ways to invoke the package functionality from command-line, including:

- running tests via npm, as explained in README; one could consider adjusting the test cases and/or writing new ones (see https://github.com/Exabyte-io/made.js/blob/master/tests/basis/basis.js, for example)
- use node executable (perhaps from the npm packages folder) and pass the desired JS file to it (see https://nodejs.dev/run-nodejs-scripts-from-the-command-line or https://stackoverflow.com/questions/32964900/how-do-you-run-a-js-file-using-npm-scripts)
- load package via another one (say https://github.com/Exabyte-io/wave.js) and use the browser console to invoke the functionality

Does this help?

**Comment by blokhin** [comment]
I just tried to do some routine computational scientist's task (_e.g._ structure format conversion, supercell generation, whatever) using this tool in a familiar "scripting" way like `node src/some_entry_point.js` but it seems it's not meant to be used like that.

**Comment by timurbazhirov** [comment]
Got it. We can consider this as a feature request.
